Usage: help COMMAND
Version: 0.6.10
Info: The commands are:

== original commands ==
  seed
  ec-to-address
  ec-to-public
  fetch-balance
  fetch-header
  fetch-height
  fetch-history
  fetch-public-key
  fetch-stealth
  fetch-tx
  fetch-tx-index
  fetch-utxo
  hd-new
  hd-private
  hd-to-ec
  hd-to-public
  help
  input-set
  input-sign
  input-validate
  mnemonic-new
  mnemonic-to-seed
  send-tx
  settings
  stealth-decode
  stealth-encode
  stealth-public
  stealth-secret
  stealth-shared
  tx-decode
  tx-encode
  tx-sign
  validate-tx

== extension commands ==
  stopall
  stop
  start
  getinfo
  getpeerinfo
  ping
  addnode
  getmininginfo
  getbestblockhash
  getbestblockheader
  fetchheaderext
  gettransaction
  backupwallet
  importwallet
  lockwallet
  exportaccountasfile
  importaccountfromfile
  importaccount
  getnewaccount
  getaccount
  deleteaccount
  lockaccount
  setaccountinfo
  listaddresses
  getnewaddress
  getaddress
  getpublickey
  getblock
  signmessage
  verifymessage
  createmultisig
  addmultisigaddress
  validateaddress
  listbalances
  getbalance
  listtxs
  xfetchbalance
  xfetchutxo
  gettx
  getaddresstx
  getaccounttx
  deposit
  send
  sendmore
  sendfrom
  listassets
  getasset
  getaddressasset
  getaccountasset
  createasset
  deleteunissuedasset
  issue
  issuefrom
  sendasset
  sendassetfrom
  getdid
  setdid
  sendwithdid
  settxfee
  getwork
  submitwork
  setminingaccount
  changepasswd
  getnewmultisig
  listmultisig
  deletemultisig
  createmultisigtx
  signmultisigtx
  getmemorypool

MVS home page: http://mvs.live